name: npm-publish
on:
  push:
    branches:
      - main # Change this to your default branch
jobs:
  deploy-storybook:
    name: deploy-storybook
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Build
        run: npm run build-storybook

      - name: Deploy
        run: npm run deploy-storybook

  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Publish if version has been updated
        uses: pascalgn/npm-publish-action@1.3.8
        with: # All of theses inputs are optional
          tag_name: 'v%s'
          tag_message: 'v%s'
          create_tag: 'true'
          commit_pattern: "^Release (\\S+)"
          workspace: '.'
          publish_command: 'npm'
          publish_args: '--non-interactive'
        env: # More info about the environment variables in the README
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this as is, it's automatically generated
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # You need to set this in your repo settings
